### ISSUE TITLE
Error: The following dependencies are imported but could not be resolved: classnames

### ISSUE THREAD

**Issue by fink-dev** [Jakhongir66/team-collaboration#19]
Hi guys, I just cloned the repo and tried to run `vite` but I got error:
>Error: The following dependencies are imported but could not be resolved:
>  classnames (imported by xxx/react_jakhongir/src/pages/TyresPage.jsx)

It looks like **classnames** package is imported on `TyresPage.jsx`:
```javascript
import { MapPinIcon, ChevronRightIcon } from '@heroicons/react/24/outline';
import React from 'react';
import classNames from 'classnames'; //<== 👈
import tyresData from '../data/tyresData.json'
``` 
But didn't see it on `package.json`:
```javascript
"dependencies": {
    "@headlessui/react": "^1.7.16",
    "@heroicons/react": "^2.0.18",
    "@reduxjs/toolkit": "^1.9.5",
    "eslint-config-react-app": "^7.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.1.1",
    "react-router-dom": "^6.14.0",
    "vite-plugin-eslint": "^1.8.1",
    "swiper": "^10.0.4"
 },
  ```
  
  So I think if you install it using npm you should install it without `--global` param.

**Comment by fink-dev** [comment]
I just installed te **classnames** package with `npm install classnames` and run `vite` again and it worked. You can assign this issue to me and I'll upload the **fix** if you want.

**Comment by Jakhongir66** [comment]
Hi

We decided remove the classname library. We do all things ourselves what do need. It is recommended to avoid excess libs.
